name: Build Test Application

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'components/**'
      - 'test_app/**'
      - '.github/workflows/build_test.yml'

jobs:
  build:
    strategy:
      matrix:
        idf_ver: ["release-v4.4", "release-v5.1", "release-v5.2", "release-v5.3", "latest"]
        idf_target: ["esp32", "esp32s2", "esp32c3", "esp32s3", "esp32p4"]
        exclude:
          - idf_ver: "release-v4.4"
            idf_target: esp32p4 # ESP32P4 support started with version 5.2
          - idf_ver: "release-v5.0"
            idf_target: esp32p4 # ESP32P4 support started with version 5.2
          - idf_ver: "release-v5.1"
            idf_target: esp32p4 # ESP32P4 support started with version 5.2
    runs-on: ubuntu-20.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v3
      - name: Build ESP-BSP Test Application
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        working-directory: test_app
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          export PEDANTIC_FLAGS="-DIDF_CI_BUILD -Werror -Werror=deprecated-declarations -Werror=unused-variable -Werror=unused-but-set-variable -Werror=unused-function"
          export EXTRA_CFLAGS="${PEDANTIC_FLAGS} -Wstrict-prototypes"
          export EXTRA_CXXFLAGS="${PEDANTIC_FLAGS}"
          idf.py build
