name: Build Test Application

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    strategy:
      matrix:
        idf_ver: ["v4.3", "release-v4.4", "latest"]
        idf_target: ["esp32", "esp32s2", "esp32c3"]
        include:
          - idf_ver: "release-v4.4"
            idf_target: esp32s3
          - idf_ver: "latest"
            idf_target: esp32s3
    runs-on: ubuntu-20.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'
      - name: Build ESP-BSP Test Application
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        shell: bash
        run: |
          cd test_app
          . ${IDF_PATH}/export.sh
          idf.py build
